### ISSUE TITLE
questions about the self-host excalidraw sites.

### ISSUE THREAD

**Issue by ozbillwang** [alswl/excalidraw.alswl.com#2]
Several questions, hope to get answered.

1. looking for a solution to deploy it via free netlify, vencel. Currently I successfully deploy the frontend via Vercel , see my blog (https://medium.com/@ozbillwang/unlocking-the-power-of-vercel-effortless-website-deployment-for-your-next-big-idea-bb507b5f84be) 

But can't make the backend work, include API, room, storage,etc. Support js deployment is harder, still can't figure out.

2. could you show me the images in https://hub.docker.com/search?q=alswl how they are built, where is their `Dockerfile`

**Comment by alswl** [comment]
@ozbillwang You should see my another project:
https://github.com/alswl/excalidraw-collaboration

Online demo(maybe not works in the future): https://excalidraw-collaboration.zeabur.app/

**Comment by ozbillwang** [comment]
yes, that's why I asked
https://github.com/alswl/excalidraw-collaboration/blob/master/docker-compose.yaml
* image: alswl/excalidraw:v0.16.1-fork-b1
* image: alswl/excalidraw-storage-backend:v2023.11.11
* image: excalidraw/excalidraw-room:sha-49bf529 (this image is fine),

But how about the other two?

**Comment by ozbillwang** [comment]
for question 1, I am looking for pure serverless solution with full functions.

I am not sure where you deploy the project `excalidraw.alswl.com` , but the storage and live collaboration functions are not working as well. 

Mine is deployed by Vercel , but with same issus as yours, except your webiste supports chinese hand-writing fonts

**Comment by alswl** [comment]
@ozbillwang 

> But how about the other two?

Haha, I will show my magic code to you:

https://github.com/alswl/excalidraw/actions/runs/6833902385/job/18586124721

https://github.com/alswl/excalidraw-storage-backend/actions/runs/6834332730/job/18586991499

**Comment by alswl** [comment]
excalidraw.alswl.com is deployed in Cloudflare Pages, it's totally frontend project, so it was static.

https://excalidraw-collaboration.zeabur.app/ is full featured demo.
